### ISSUE TITLE
mapAlert brakes tab switching on a bell

### ISSUE THREAD

**Issue by barlik** [mina86/urxvt-tabbedex#11]
Step to replicate:

Open new tab and type:
```
sleep 5; echo -e '\a'
```
Then switch back to the first tab and wait 5 seconds. After five seconds, you can't change back to tab number two. Cursor indicates that terminal doesn't have input focus (cursor is hollow).

**Comment by mina86** [comment]
Could you also post `xrdb -query`?

**Comment by barlik** [comment]
Removing xrdb resources one by one, I've found the culprit. It's the `URxvt.mapAlert: true` resource.
If I disable it, tab switching works fine and I still have the focus.

**Comment by barlik** [comment]
I've just tried the original tabbed plugin and it suffers from the same issue.

**Comment by mina86** [comment]
On Mon, Aug 15 2016, Barlik wrote:
>It's the `URxvt.mapAlert: true` resource.
> If I disable it, tab switching works fine and I still have the focus.

Weirdly, I cannot reproduce this even with the resource set.

**Comment by barlik** [comment]
Be sure to type sleep and echo on the last opened tab and switch to the other tab. By the way, is there a way to disable the bell command, I've tried setting bell-timeout to 0, but it didn't work.

**Comment by mina86** [comment]
I can reproduce it. Thanks. You should be able to click on the tab in the tab bar to un-break tabbedex. I’m not sure how to deal with it at this time. For now I’ll try to submit a patch that disables mapAlert, but that’s not a satisfactory solution.

**Comment by barlik** [comment]
Thanks

**Comment by mina86** [comment]
Actually I’ve fixed the issue. See commit 8129bc263126fdb61fd5b045e3e71b5a6cec062a.

**Comment by barlik** [comment]
Great, thanks a lot!

I've tested it, works wonderfully!
