### ISSUE TITLE
Mistake in documentation section for custom prefix

### ISSUE THREAD

**Issue by shef-er** [mina86/urxvt-tabbedex#12]
Mistake in documentation section:

 By default tabbedex uses the same prefix for resource names as tabbed plugin.
 If this is not desired, the resource can be used to set a new prefix, for 
 example:

    URxvt.tabbed.tabbedex-rs-prefix: tabbedex

    ! Affects tabbed only:
    URxvt.tabbed.tabbar-fg: 4
    URxvt.tabbed.tabbar-bg: 0

    ! Affects tabbedex only:
    URxvt.tabbed.tabbar-fg: 5
    URxvt.tabbed.tabbar-bg: 0
(+    URxvt.tabbedex.tabbar-fg: 5)
(+    URxvt.tabbedex.tabbar-bg: 0)

**Comment by mina86** [comment]
Thanks. Fixed.
