### ISSUE TITLE
Messing around with extension and now custom tab don't work

### ISSUE THREAD

**Issue by rudevdr** [mina86/urxvt-tabbedex#16]
Everything was working smoothly until I tried playing with the extension. I think I may have deleted some wrong files and now pressing ctrl-t doesn't open new tab anymore. The default mapping however do work fine. How can I fix this please? 

	*background:	#282828
	*color0:	#282828
	*color1:	#cc241d
	*color10:	#b8bb26
	*color11:	#fabd2f
	*color12:	#83a598
	*color13:	#d3869b
	*color14:	#8ec07c
	*color15:	#ebdbb2
	*color2:	#98971a
	*color3:	#d79921
	*color4:	#458588
	*color5:	#b16286
	*color6:	#689d6a
	*color7:	#a89984
	*color8:	#928374
	*color9:	#fb4934
	*foreground:	#ebdbb2
	URxvt*pointerBlank:	true
	URxvt*scrollTtyKeypress:	true
	URxvt*scrollTtyOutput:	false
	URxvt*scrollWithBuffer:	true
	URxvt*termName:	rxvt-unicode-256color
	URxvt.boldFont:	xft:Hack-Bold:pixelsize=14:weight=bold,xft:Symbola
	URxvt.borderless:	true
	URxvt.cursorBlink:	true
	URxvt.font:	xft:Hack-Regular:pixelsize=14,xft:Symbola
	URxvt.geometry:	120x40
	URxvt.iso14755:	false
	URxvt.iso14755_52:	false
	URxvt.italicFont:	xft:Hack-RegularOblique:pixelsize=14:slant=italic,xft:Symbola
	URxvt.keysym.Control-0:	perl:tabbedex:goto_tab_10
	URxvt.keysym.Control-1:	perl:tabbedex:goto_tab_1
	URxvt.keysym.Control-2:	perl:tabbedex:goto_tab_2
	URxvt.keysym.Control-3:	perl:tabbedex:goto_tab_3
	URxvt.keysym.Control-4:	perl:tabbedex:goto_tab_4
	URxvt.keysym.Control-5:	perl:tabbedex:goto_tab_5
	URxvt.keysym.Control-6:	perl:tabbedex:goto_tab_6
	URxvt.keysym.Control-7:	perl:tabbedex:goto_tab_7
	URxvt.keysym.Control-8:	perl:tabbedex:goto_tab_8
	URxvt.keysym.Control-9:	perl:tabbedex:goto_tab_9
	URxvt.keysym.Control-j:	perl:tabbedex:prev_tab
	URxvt.keysym.Control-k:	perl:tabbedex:next_tab
	URxvt.keysym.Control-t:	perl:tabbedex:new_tab
	URxvt.keysym.Shift-Control-C:	eval:selection_to_clipboard
	URxvt.keysym.Shift-Control-V:	eval:paste_clipboard
	URxvt.mouseWheelScrollPage:	true
	URxvt.perl-ext-common:	default,tabbedex,matcher,selection-to-clipboard,resize-font
	URxvt.saveLines:	100000
	URxvt.scrollBar:	false
	URxvt.shading:	20
	URxvt.tabbed.tabbedex-rs-prefix:	tabbedex
	URxvt.tabbedex.autohide:	true
	URxvt.tabbedex.bell-bg:	2
	URxvt.tabbedex.bell-fg:	0
	URxvt.tabbedex.bell-tab-bg:	2
	URxvt.tabbedex.bell-tab-fg:	0
	URxvt.tabbedex.bell-timeout:	1
	URxvt.tabbedex.tab-bg:	0
	URxvt.tabbedex.tab-fg:	15
	URxvt.tabbedex.tabbar-bg:	0
	URxvt.tabbedex.tabbar-fg:	2
	URxvt.transparent:	false
	URxvt.urgentOnBell:	true
	Xft.antialias:	1
	Xft.autohint:	0
	Xft.hinting:	1
	Xft.hintstyle:	hintslight
	Xft.lcdfilter:	lcddefault
	Xft.rgba:	rgb
	floating_no_border.keysym.Control-0:	perl:tabbedex:goto_tab_10
	floating_no_border.keysym.Control-1:	perl:tabbedex:goto_tab_1
	floating_no_border.keysym.Control-2:	perl:tabbedex:goto_tab_2
	floating_no_border.keysym.Control-3:	perl:tabbedex:goto_tab_3
	floating_no_border.keysym.Control-4:	perl:tabbedex:goto_tab_4
	floating_no_border.keysym.Control-5:	perl:tabbedex:goto_tab_5
	floating_no_border.keysym.Control-6:	perl:tabbedex:goto_tab_6
	floating_no_border.keysym.Control-7:	perl:tabbedex:goto_tab_7
	floating_no_border.keysym.Control-8:	perl:tabbedex:goto_tab_8
	floating_no_border.keysym.Control-9:	perl:tabbedex:goto_tab_9

This is my `xrdb -query -all`. Thank you!

**Comment by akrus** [comment]
Probably you just installed updates :)
Just delete perl: in front of perl:tabbedex:new_tab.
e.g.
```
URxvt.keysym.Control-t: tabbedex:new_tab
```

**Comment by rudevdr** [comment]
Thank you very much! I didn't know that and it fixed the issue.

**Comment by mina86** [comment]
Fixed in https://github.com/mina86/urxvt-tabbedex/releases/tag/v18.406
