### ISSUE TITLE
Open new tab in same directory

### ISSUE THREAD

**Issue by rudevdr** [mina86/urxvt-tabbedex#17]
I have `URxvt.keysym.Control-t: tabbedex:new_tab` in my `.Xdefaults` so whenever I press `Ctrl-t` a new tab is opened. But I also want to open new tab and cd into the directory where the button was pressed. 

For eg. If I am in a tab with dir `/home/user/music/` and if I press `Ctrl-Shift-t` then a new tab should be opened and current directory is changed to `/home/user/music/`. 

I see that issue #13 asks for same feature was closed 4 months ago with some information about `pgid-cd.pl` file but I am unable to implement it. Any help will be appreciated, thanks!

**Comment by mina86** [comment]
`pgid-cd.pl` has documentation in it’s source which includes examples of use:

    URxvt.tabbedex.tab-arguments: \
        -e %~/.urxvt/tabbedex-pgid-cd %p %E

This would make it work for any way you open a tab. If you want this effect only when some key-bindings are used, you need an argument passed to the `new_tab` action, e.g.:

    URxvt.keysym.Control-t: \
        tabbedex:new_tab: -e %~/.urxvt/tabbedex-pgid-cd %p %E

**Comment by mina86** [comment]
That should work. Is a new tab being created at all? Could you start the terminal from another terminal to see any error messages printed?

**Comment by rudevdr** [comment]
Ah, of course. I didn't make the script executable. Thanks a lot for your help.
