### ISSUE TITLE
tab-arguments issue

### ISSUE THREAD

**Issue by mentrelli** [mina86/urxvt-tabbedex#18]
In my .Xdefaults I added these two lines:
```
URxvt.keysym.Control-t: \
    tabbedex:new_tab: -e %~/.urxvt/tabbedex-pgid-cd %p %E

URxvt.tabbedex.tab-arguments: \
    -e %~/.urxvt/tabbedex-pgid-cd %p %E

```
Opening a new tab with `Ctrl+t` works as expected (the new tab is opened in the same directory as the previous one), but if I open a tab with `Shit+Down`, the new tab is opened in the home directory. 
More in general, whatever I specify as tab-arguments seems to be ignored. Even with
```
URxvt.tabbedex.tab-arguments: \
        -e /bin/sh %~/.urxvt/command-runner.sh %n %E
```
the script seems to be ignored (everything else works fine, as far as tabbedex is concerned). Any idea why? Thanks.

**Comment by mentrelli** [comment]
> $ xrdb -query
> *customization:	-color
> Xft.dpi:	105.599609375
> Xft.antialias:	1
> Xft.hinting:	1
> Xft.hintstyle:	hintslight
> Xft.rgba:	rgb

When I start urxvt from another terminal emulator, there are no messages at all being printed.

I also noticed that the resource
`URxvt.tabbedex.title: false`
seems to be ignored as well (no matter how I set it - true or false - the title is always there).

**Comment by mina86** [comment]
Try `xrdb -merge ~/.Xdefaults` and `echo URxvt.tabbed.tabbedex-rs-prefix: % | xrdb -merge`. It could be a difference in how configuration in `~/.Xdefaults` and the ones in X resource database are handled.

**Comment by mentrelli** [comment]
The problem is still there... after `echo URxvt.tabbed.tabbedex-rs-prefix: % | xrdb -merge` urxvt does not even start; I had to restart

**Comment by mina86** [comment]
This is very strange. I don’t see how that could make urxvt fail to start. Are there any messages displayed in the console in the above scenario when urxvt fails to start?

You can reset your XRDB by running `xrdb /dev/null`, no need for a restart (though that will loose your xft configuration).

What’s the contents of your `.Xdefaults`?

**Comment by mina86** [comment]
Closing for the time being. If this is still an issue, please reopen.
