### ISSUE TITLE
Not an issue: How to start urxvt with multiple named tabs

### ISSUE THREAD

**Issue by dxxvi** [mina86/urxvt-tabbedex#19]
Hi, is it possible to start urxvt with multiple tabs with different names in different directories? For example, I'd like to start with 3 tabs: the 1st tab in directory /dev/shm with name of 'Tab 1', the 2nd in /home with name of 'Tab 2' and the 3rd in /root with name of 'Tab 3'.

**Comment by mina86** [comment]
It’s not possible to automatically open three tabs when urxvt starts
but it is possible to configure things such that the first three tabs
conform to what you’ve described. To do that you’ll have to take
advantage of `command-runner.sample` and configure its predefined
commands as follows:

```
set_name() {
	printf '\033]777;tabbedx;set_tab_name;%s\007' "$1"
}

case $id in
0)
	set_name 'Tab 1'
	cd /dev/shm
	;;
1)
	set_name 'Tab 2'
	cd /home
	;;
2)
	set_name 'Tab 3'
	cd /root
esac
exec "$@"
```

Consult the `command-runner.sample` file for documentation of how to
wire it with tabbedex.
