### ISSUE TITLE
no-tabbedex-keys does not disable built-in keybindings

### ISSUE THREAD

**Issue by coolsa** [mina86/urxvt-tabbedex#24]
With the setting ` URxvt.tabbedex.no-tabbedex-keys: true` , the default keybindings still exist.

The expected behaviour is that when the no-tabbedex-keys is set to true, things like Control-Left should not move my tab around, but the original behaviour still occurs.

my full configuration (from xrdb -query -all)
```URxvt.font:	xft:Dejavu Sans Mono:pixelsize=20
URxvt.letterSpace:	-1
URxvt.scrollBar:	FALSE
URxvt.perl-ext:	tabbedex,eval
URxvt.iso14755:	false
URxvt.iso14755_52:	false
URxvt.keysym.M-Control-V:	eval:paste_clipboard
URxvt.keysym.M-Control-C:	eval:selection_to_clipboard
URxvt.tabbedex.no-tabbedex-keys:	true
URxvt.keysym.Shift-Control-T:	tabbedex:new_tab
URxvt.keysym.Shift-Control-W:	tabbedex:kill_tab
URxvt.keysym.Shift-Control-Left:	tabbedex:prev_tab
URxvt.keysym.Shift-Control-Right:	tabbedex:next_tab
URxvt.keysym.Shift-Control-Page_Down:	tabbedex:move_tab_left
URxvt.keysym.Shift-Control-Page_Up:	tabbedex:move_tab_right
*.foreground:	#e6e1dc
*.background:	#2b2b2b
*.cursorColor:	#e6e1dc
*.color0:	#2b2b2b
*.color8:	#5a647e
*.color1:	#da4939
*.color9:	#da4939
*.color2:	#a5c261
*.color10:	#a5c261
*.color3:	#ffc66d
*.color11:	#ffc66d
*.color4:	#6d9cbe
*.color12:	#6d9cbe
*.color5:	#b6b3eb
*.color13:	#b6b3eb
*.color6:	#519f50
*.color14:	#519f50
*.color7:	#e6e1dc
*.color15:	#f9f7f3
```

**Comment by mina86** [comment]
Could you try removing the `Shift-Control-*` bindings and see if the built-in keysyms work? My first guess is that urxvt matches on `Shift-X` when `X` is pressed but there is no mapping for unshifted `X`. Dunno though. I'll try to take a closer look at it over the weekend.

**Comment by mina86** [comment]
Sorry about the long delay. The actual issue was due to `tabbedex-rs-prefix` confusion. You were missing:
```Urxvt.tabbed.tabbedex-rs-prefix: %```
in your configuration which made the extension read `URxvt.tabbed.no-tabbedex-keys` resource. This behaviour has been deprecated for quite a while now so I’ve changed the code to always prefer `tabbedex` prefix.

To address your issue, either pull newest version from HEAD or add the `tabbedex-rs-prefix` resource as described above.
