### ISSUE TITLE
Using urxvtd gives an error: Can't call method "is_being_renamed" on an undefined value at line 715.

### ISSUE THREAD

**Issue by lozdreamz** [mina86/urxvt-tabbedex#25]
For testing I starting urxvt daemon with `urxvtd -q -f -o`
tabbedex is installed and enabled in my .Xdefaults
urxvt client is started with `urxvtc`
First run is working fine but all next runs give a terminal window with frozen cursor and urxvtd throw an error:
`urxvt: urxvt::timer callback evaluation error: Can't call method "is_being_renamed" on an undefined value at /usr/lib/urxvt/perl/tabbedex line 715.`
I don't know Perl well enough to fix this error.

**Comment by mina86** [comment]
Sorry about the delay. This should now be fixed.

**Comment by lozdreamz** [comment]
Great! Thank you
