### ISSUE TITLE
tabbedex runs the command given with cli arguments on all tabs.

### ISSUE THREAD

**Issue by GasparVardanyan** [mina86/urxvt-tabbedex#28]
For example when I run urxvt with this command:
urxvt -e sh -c "ls; read"
And then when I create a new tab with Shift+Down (tabbedex:new_tab), tabbedex opens new tab and executes _sh -c "ls; read"_.
The expected result was the opening of a new empty tab without executing any commands.

**Comment by mina86** [comment]
That’s expected behaviour. `-e` will affect all tabs. Depending on what you want to achieve exactly, `command-runner.sample` may be of help. You can also configure Shift+Down to ignore `-e` flag with:
```    URxvt.keysym.Shift-Down: tabbedex:new_tab:-e /bin/bash```

**Comment by GasparVardanyan** [comment]
Thank you.

**Comment by GasparVardanyan** [comment]
Is there any way to automatically detect the shell?
...-e $SHELL doesn't work

**Comment by mina86** [comment]
tabbedex won’t perform environment variable expansion but you can wrap it in a call to shell:
```
URxvt.keysym.Shift-Down: tabbedex:new_tab:-e /bin/sh -c 'exec ${SHELL:-/bin/sh}'
```

**Comment by GasparVardanyan** [comment]
Thank you.
