### ISSUE TITLE
How to show current working directory name in the tab name?

### ISSUE THREAD

**Issue by ProgrammingLife** [mina86/urxvt-tabbedex#36]
How to show current working directory name (without a path) in the tab name?

**Comment by mina86** [comment]
To change tab’s name, you need to use `set_tab_name` OSC sequence.
This is documented in the man page and it’s usage from a shell is:

    printf '\033]777;tabbedex;set_tab_name;%s\007' "foo"

If you’re using bash, this can be used either through `PS1` variable
like so:

    PS1=$PS1'\[\e]777;tabbedex;set_tab_name;\W\a\]'

or using a prompt command function like so:

    set_tab_name_to_wd() {
        case $PWD in
        "$HOME") __wd='~'; ;;
        *) __wd=${PWD##*/}
        esac
        printf '\033]777;tabbedex;set_tab_name;%s\007' "${__wd:-/}"
    }
    PROMPT_COMMAND=set_tab_name_to_wd

Just add either of those to `~/.bashrc` and you’re set.  For other
shells refer to their documentation to figure out `PS1` control codes
or how to invoke commands when prompt is displayed.

The one caveat is that this sets the name to the working directory of
the shell process and does not update the name if program invoked from
the shell changes its working directory.  This may or may not be what
you want.
