### ISSUE TITLE
Is it possible to set custom font size for a tab title?

### ISSUE THREAD

**Issue by ProgrammingLife** [mina86/urxvt-tabbedex#37]
Is it possible to set custom font size for a tab title?

P.S. Thanks for the great urxvt addon!

**Comment by mina86** [comment]
That’s not possible and it’s a feature that I don’t envision tabbedex will ever have.

**Comment by ProgrammingLife** [comment]
@mina86 I'm just curious about that fact: if we increase or decrease urxvt font then tabbedex still have the same font size so that means tabbedex uses initial font size. So if we set initial font size for urxvt then we can change font size manually or change it on new tab created event. Not sure if it has any common sense to do like that :)

**Comment by mina86** [comment]
Yes, that’s true and I have contemplated doing it that way (or actually the opposite way by specifying font or the tab bar). That would, however, open a can of warms when dealing with sizing. For example, how to deal with tab bar hiding when font heights are different. There were already various reports of empty lines being drawn at the bottom of the window so I don’t really want to complicate the code even further.

Perhaps I was too definite in my statement. Nonetheless, I don’t envision myself implementing that feature and if someone wants to send patches I’ll be very picky about them. ;)
