### ISSUE TITLE
Create layout with multiple tabs on startup

### ISSUE THREAD

**Issue by kootenpv** [mina86/urxvt-tabbedex#38]
I guess what would help, is when I could somehow create a window with 4 named tabs in it.

Something like this (pseudo):

```
new window
rename tab a
cd some_location && run_some_command
new tab
rename tab b 
cd some_other_location && run_some_command
new tab
rename tab c
cd some_other_location && run_some_command
new tab
rename tab d
cd some_other_location && run_some_command
```

**Comment by mina86** [comment]
You almost can. You can sat `tab-arguments` to:

    URxvt.tabbedex.tab-arguments: \
        -e /bin/sh %~/.urxvt/command-runner.sh %n %E

copy `command-runner.sample` to `~/.urxvt/command-runner.sh` and customise it to do the renaming and starting of custom commands. You can rename tabs with

    printf '\033]777;tabbedex;set_tab_name;%s\007' "foo"

**Comment by kootenpv** [comment]
Wow thanks for your quick reply and adding the renaming!

I am not able to figure out exactly what 

```bash
URxvt.tabbedex.tab-arguments: \
    -e /bin/sh %~/.urxvt/command-runner.sh %n %E
```

is. I know it should probably go in .Xresources, though.

But what would it do? Every time a new tab opens, the command-runner script will run, or what?

**Comment by mina86** [comment]
Correct. With that X resource set, every time a new tab is created, instead of starting a shell in it, `~/.urxvt/command-runner.sh` will be run with first argument being number of tabs started so far and the rest of the arguments being the default command term would run if `tab-arguments` wasn’t set. The `command-runner.sh` can than do different things depending on the first argument such as naming tabs or running different commands in the first few tabs.

**Comment by kootenpv** [comment]
Wow, that makes it really clear. Thanks!

**Comment by mina86** [comment]
If you want to start a new terminal window with four named tabs running specified commands (which is how I understood your initial post), you’d set `tab-arguments` to point at a customised `command-runner` which starts those four commands. There’s no way to instruct tabbedex to open multiple tabs at startup, so you’d have to manually open three more tabs but the end result would be four tabs each with particular name and command.

Note that you can have different Xresources configuration by using different prefixes and different names. For example, by putting:

    URxvt.tabbedex.tab-arguments: -e /bin/bash
    ZRxvt.tabbedex.tab-arguments: -e /bin/zsh
    
in resources you can start urxvt as either of:

    urxvt
    urxvt -name ZRxvt

Lastly, note that you can bind different keys to creating tabs with different commands. For example with the following:

    URxvt.keysym.F1:    tabbedex:new_tab:-e info

pressing F1 will start info in a new tab.

**Comment by kootenpv** [comment]
This is super helpful! Thanks so much for helping out. Mayb interesting to document these tricks (or perhaps I have not succesfully been looking around enough)

**Comment by mina86** [comment]
All of it is documented though it is true that to get a full picture you have to go through urxvt and tabbedex documentation to know that you can fit those pieces together. I try to put examples in commit messages in documentation but things could always be improved. Issue is that I’m not a great technical writer and don’t really have spare time to go through all the documentation to figure out how best to improve it.

**Comment by kootenpv** [comment]
That problem is really familiar to me... I think the worst is creating a first version, closely followed by maintaining it...
