### ISSUE TITLE
[Documentation] Would it be possible for the README to say for which rxvt-unicode version this could work?

### ISSUE THREAD

**Issue by rubyFeedback** [mina86/urxvt-tabbedex#40]
See title. I had some old rxvt from 2016 I think; copy/pasting the examples from the README
did not work. I got a help screen output when I tried to one command where it is enabled
after installation (the curl command worked fine).

**Comment by rubyFeedback** [comment]
Actually I think I had --disable-perl accidentally for my compiled rxvt-unicode, so perhaps
this was why the command did not work. So, user error I suppose. :)

**Comment by mina86** [comment]
> rxvt from 2016

That’s the newest unicode-urxvt version.
